server:
  port: 8080

spring:
  application:
    name: URL-Shortener

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5431/url_shortener}
    username: ${SPRING_DATASOURCE_USERNAME:url_shortener_user}
    password: ${SPRING_DATASOURCE_PASSWORD:url_shortener_pass}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD:}
      ssl:
        enabled: ${SPRING_DATA_REDIS_SSL:false}

  cache:
    type: redis

  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      properties:
        retry.backoff.ms: 200
        retry.backoff.max.ms: 2000
        enable.idempotence: true
    consumer:
      group-id: analytics-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

management:
  endpoint:
    health:
      show-details: never
      show-components: never
      probes:
        enabled: false
  endpoints:
    web:
      exposure:
        include: health

app:
  base-url: ${APP_BASE_URL:http://localhost:8080}
  rate-limit:
    requests-per-minute: ${RATE_LIMIT:20}
